# reload shorcut
unbind r
bind r source-file ~/.tmux.conf\; display 'Reloaded tmux configuration'

# prefix key
unbind-key 'M-\'
set-option -g prefix 'M-\'

# general settings
set-option -g base-index 1
set-option -g escape-time 0
set-option -g mouse on
set-option -g pane-base-index 1
set-option -g renumber-windows on

# make home and end work
bind-key -n End send Escape "OF"
bind-key -n Home send Escape "OH"

# window cycling
bind-key -n 'C-S-Tab' previous-window
bind-key -n 'C-Tab' next-window
bind-key 'M-n' next-window
bind-key 'M-p' previous-window
bind-key 'n' next-window
bind-key 'p' previous-window

# window creation
bind-key -n 'C-S-T' new-window
bind-key -n 'C-S-W' kill-window

# window splitting
bind-key -n 'M-s' split-window -v
bind-key -n 'M-v' split-window -h -b
bind-key -n 'M-S' split-window -v -b
bind-key -n 'M-V' split-window -h

# pane cycling
bind-key 'M-\' select-pane -t :.+
bind-key -n 'M-h' select-pane -L
bind-key -n 'M-j' select-pane -D
bind-key -n 'M-k' select-pane -U
bind-key -n 'M-l' select-pane -R

# interative selection
bind-key -n 'M-b' choose-tree -Z

# bottom popup
bind-key -n 'M-w' display-popup -y 100% -w 100% -h 30% -d "#{pane_current_path}"
bind-key -n 'M-W' split-window -v -l 30% -c "#{pane_current_path}"

# color options
set-option -g default-terminal "${TERM}"
set-option -sg terminal-overrides ",*:RGB"

# colors
BLACK='#000000'
BLUE='#3b78ff'
DARK_GRAY='#454545'
GRAY='#777777'
LIGHT_GRAY='#bbbbbb'
WHITE='#ffffff'

# styling
set-option -g status-position top
set-window-option -g pane-border-style "fg=$DARK_GRAY"
set-window-option -g pane-active-border-style "fg=$BLUE"
set-window-option -g status-left ''
set-window-option -g status-right "#[fg=$WHITE,bg=$BLUE] Session #[fg=$LIGHT_GRAY,bg=$BLACK] #{session_name} "
set-window-option -g status-style "bg=$BLACK"
set-window-option -g status-left-style "bg=$BLACK"
set-window-option -g status-right-style "bg=$BLACK"
set-window-option -g window-status-style "fg=$GRAY,bg=$BLACK"
set-window-option -g window-status-current-format "#[fg=$WHITE,bg=$BLUE] #{window_index} #[fg=$LIGHT_GRAY,bg=$BLACK] #{window_name}"
set-window-option -g window-status-format "#[fg=$BLACK,bg=$DARK_GRAY] #{window_index} #[fg=$GRAY,bg=$BLACK] #{window_name}"
